-- ============================================================================
-- Secure Premium PDF Storage
-- 
-- Creates private storage bucket for premium PDFs with RLS policies
-- and signed URL generation function
-- ============================================================================

-- ============================================================================
-- Create private storage bucket for premium PDFs
-- ============================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('premium-pdfs', 'premium-pdfs', false)
ON CONFLICT (id) DO UPDATE SET public = false;

-- ============================================================================
-- Storage RLS Policy: Only authenticated users can access
-- (actual entitlement check happens in the Edge Function)
-- ============================================================================

-- Allow authenticated users to read (download) - entitlement check in app layer
CREATE POLICY "Authenticated users can read from premium-pdfs"
ON storage.objects
FOR SELECT
TO authenticated
USING (bucket_id = 'premium-pdfs');

-- Allow service role full access (for uploads)
CREATE POLICY "Service role has full access to premium-pdfs"
ON storage.objects
FOR ALL
TO service_role
USING (bucket_id = 'premium-pdfs')
WITH CHECK (bucket_id = 'premium-pdfs');

-- Deny anonymous/public access
CREATE POLICY "Anonymous users cannot access premium-pdfs"
ON storage.objects
FOR SELECT
TO anon
USING (false);

-- ============================================================================
-- PDF Asset Registry Table
-- Maps topic PDFs to storage paths with metadata
-- ============================================================================
CREATE TABLE IF NOT EXISTS pdf_assets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  file_key TEXT NOT NULL UNIQUE,           -- Storage path/filename
  title TEXT NOT NULL,                      -- Display title
  topic_id TEXT,                            -- Associated topic (optional)
  category_id TEXT,                         -- Associated category
  is_premium BOOLEAN NOT NULL DEFAULT true, -- Whether this requires paid access
  is_public_sample BOOLEAN DEFAULT false,   -- Whether this is a free sample
  storage_path TEXT NOT NULL,               -- Full storage path
  file_size INTEGER,                        -- File size in bytes
  content_type TEXT DEFAULT 'application/pdf',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE pdf_assets ENABLE ROW LEVEL SECURITY;

-- Everyone can read PDF metadata (not the files themselves)
CREATE POLICY "Anyone can read pdf_assets metadata"
ON pdf_assets
FOR SELECT
TO anon, authenticated
USING (true);

-- Only service role can modify
CREATE POLICY "Only service role can modify pdf_assets"
ON pdf_assets
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Create index for topic lookups
CREATE INDEX IF NOT EXISTS idx_pdf_assets_topic_id ON pdf_assets(topic_id);
CREATE INDEX IF NOT EXISTS idx_pdf_assets_is_premium ON pdf_assets(is_premium);

-- ============================================================================
-- Function: get_pdf_download_url
-- Generates signed URL for PDF download with entitlement check
-- ============================================================================
CREATE OR REPLACE FUNCTION get_pdf_download_url(
  p_user_id UUID,
  p_file_key TEXT,
  p_expiry_seconds INTEGER DEFAULT 300  -- 5 minutes default
)
RETURNS TABLE (
  success BOOLEAN,
  signed_url TEXT,
  error TEXT
) AS $$
DECLARE
  v_has_premium BOOLEAN;
  v_is_public BOOLEAN;
  v_pdf_record RECORD;
BEGIN
  -- Get PDF record
  SELECT * INTO v_pdf_record
  FROM pdf_assets
  WHERE file_key = p_file_key;
  
  IF NOT FOUND THEN
    RETURN QUERY SELECT false, NULL::TEXT, 'PDF not found'::TEXT;
    RETURN;
  END IF;
  
  -- Check if public sample
  IF v_pdf_record.is_public_sample THEN
    -- Public samples don't need entitlement check
    -- But we still generate signed URL for tracking consistency
    RETURN QUERY SELECT 
      true, 
      NULL::TEXT,  -- Will be generated by Edge Function
      NULL::TEXT;
    RETURN;
  END IF;
  
  -- Check if user has premium access
  SELECT has_premium_access(p_user_id) INTO v_has_premium;
  
  IF NOT v_has_premium THEN
    RETURN QUERY SELECT false, NULL::TEXT, 'Premium access required'::TEXT;
    RETURN;
  END IF;
  
  -- User has access - return success (signed URL generated by Edge Function)
  RETURN QUERY SELECT true, NULL::TEXT, NULL::TEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permissions
GRANT EXECUTE ON FUNCTION get_pdf_download_url(UUID, TEXT, INTEGER) TO authenticated;
GRANT EXECUTE ON FUNCTION get_pdf_download_url(UUID, TEXT, INTEGER) TO service_role;

-- ============================================================================
-- Update PDF download events table to track secure downloads
-- ============================================================================

-- Add column for secure delivery method if not exists
ALTER TABLE pdf_download_events 
ADD COLUMN IF NOT EXISTS delivery_method TEXT DEFAULT 'signed_url' 
  CHECK (delivery_method IN ('signed_url', 'direct', 'public'));

-- Add column for access granted status
ALTER TABLE pdf_download_events 
ADD COLUMN IF NOT EXISTS access_granted BOOLEAN DEFAULT true;

-- ============================================================================
-- Insert current PDFs into registry (premium by default)
-- Run this after uploading files to storage
-- ============================================================================

-- Note: After uploading PDFs to the 'premium-pdfs' bucket,
-- insert records here:
-- INSERT INTO pdf_assets (file_key, title, topic_id, category_id, storage_path, is_premium)
-- VALUES 
--   ('Kitchen_Household_Interview_Practice_Questions.pdf', 'Kitchen & Household', 'kitchen-household', 'home-living', 'premium-pdfs/Kitchen_Household_Interview_Practice_Questions.pdf', true),
--   ... etc

-- ============================================================================
-- Function to populate pdf_assets from existing topics (run once)
-- ============================================================================
CREATE OR REPLACE FUNCTION populate_pdf_assets_from_topics()
RETURNS VOID AS $$
BEGIN
  -- This would be called after the migration to populate the registry
  -- based on existing topic data
  -- Implementation depends on how topics are stored
  NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON TABLE pdf_assets IS 'Registry of PDF files with premium/public classification for secure delivery';
COMMENT ON COLUMN pdf_assets.is_premium IS 'If true, requires paid subscription to download';
COMMENT ON COLUMN pdf_assets.is_public_sample IS 'If true, available without subscription (free sample)';
